### ISSUE TITLE
fusermount: user has no write access to mountpoint /data

### ISSUE THREAD

**Issue by cookandy** [tynor88/docker-rclone-mount#2]
Hello,

I'm having a problem mounting my grdive. I'm pretty sure it was working a few weeks ago. I tried removing and installing from the latest template, but I'm getting this error 

 ```
Executing => rclone mount --config=/config/.rclone.conf --allow-other --read-only gcrypt-direct: /data
2019/02/22 22:12:08 mount helper error: fusermount: user has no write access to mountpoint /data
2019/02/22 22:12:08 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```

I'm running on the latest dev version and am using this startup command

```
--cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfine -v /mnt/disks/rclone_volume/:/data:shared
```

I tried using `rw` instead of `shared`, but it didn't help.

Any ideas?

**Comment by tynor88** [comment]
You have Wrong permissions on the host that /data mounts to.

tir. 5. mar. 2019 22.09 skrev cookandy <notifications@github.com>:

**Comment by cookandy** [comment]
Thanks, `chmod 777 /mnt/disks/rclone_volume` seems to have fixed it!

**Comment by JsBergbau** [comment]
Also fuse mount does not like when directory was modified with `chattr +i`.

**Comment by tynor88** [comment]
Explain?

**Comment by JsBergbau** [comment]
By habit I set `chattr +i` for all mountpoints. This prevents writing data to root filesystem when not mounted. So I did for a fuse mount moint. After removing via `chattr -i` I could mount again.

**Comment by tynor88** [comment]
Why not just mount with readonly? Wouldnt it effectively do the same thing?
________________________________
Fra: JsBergbau ***@***.***>
Sendt: 17. juli 2022 09:32
Til: tynor88/docker-rclone-mount ***@***.***>
Cc: tynor88 ***@***.***>; Comment ***@***.***>
Emne: Re: [tynor88/docker-rclone-mount] fusermount: user has no write access to mountpoint /data (#2)


By habit I set chattr +i for all mountpoints. This prevents writing data to root filesystem when not mounted. So I did for a fuse mount moint. After removing via chattr -i I could mount again.

**Comment by JsBergbau** [comment]
I think there is a misunderstanding.
When mounting via normal mount command like `mount /dev/sda ~/mnt` chattr works perfectly. You can read and write from and to `~/mnt`. But when sda is not mounted, you can't write to `~/mnt`. So you prevent that writes go to your root filesystem and filling it up.

Mounting readonly is completly different.

**Comment by tynor88** [comment]
What is the use case? 🙂 just curious.

**Comment by felrock** [comment]
Had the same issue, turns out it was a typo on the IdentityFile, sshfs just continues as usual and does not notify the user if the IdentityFile is not found.
